name: 'tickets'
version: 0.0.1
description: A ticket commerce application
author: Jack Murphy jack@rightisleft.com
homepage: https://www.rightisleft.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
#Server Dependencies
  barback: ">=0.15.2+2 <0.16.0"
  json_object: "1.0.19"
  mongo_dart:
    git: "https://github.com/Pacane/mongo_dart"
  connection_pool: "0.1.0+2"
  dartson: "0.2.5"
  guinness: "0.1.17"
  html: "0.12.2"
  shelf: '>=0.6.2 <0.7.0'
  shelf_static: "0.2.2"
  shelf_route: "0.14.0"
#Client Dependencies
  bootjack: "0.6.5"
  browser: ">=0.10.0+2 <0.11.0"
  intl: "0.12.4+2"
  sass: "0.4.2"
  angular2: "2.0.0-alpha.45"
  unittest: "0.11.6+1"
transformers:
- tickets
- dartson
- sass:
      executable: sassc     # Sass executable to use
- angular2:
    entry_points:
        - web/main.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
